### ISSUE TITLE
Trying to bootstrap without SDL2 installed gives somewhat opaque error

### ISSUE THREAD

**Issue by kristomu** [cknave/kevedit#16]
If I try to run bootstrap on a computer that doesn't have SDL2 installed, the console outputs the following:

```
bootstrap.sh: Running aclocal...
configure.ac:31: warning: macro 'AM_PATH_SDL2' not found in library
bootstrap.sh: Running autoconf...
configure.ac:23: error: possibly undefined macro: AC_MSG_NOTICE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:31: error: possibly undefined macro: AM_PATH_SDL2
```

which is a bit hard to figure out what means without doing a web search. Usually, missing library errors are reported when running ./configure; could that be done with SDL2 too?

**Comment by cknave** [comment]
I've updated the build scripts to produce a source distribution that includes the `configure` script. The most recent one is at https://github.com/cknave/kevedit/releases/download/1.0.7/kevedit-1.0.7.tar.gz

I also updated the README to call out the requirements when building from git.
