### ISSUE TITLE
Fix .desktop file for AppImage

### ISSUE THREAD

**Issue by probonopd** [cknave/kevedit#2]
Please provide the AppImage for download on GitHub Releases, thanks.

**Comment by cknave** [comment]
New set of binaries (including x86_64 AppImage) will be up for the next version bump, hopefully in the next couple of days.

**Comment by cknave** [comment]
1.0.0 binaries are available now

**Comment by probonopd** [comment]
Thank you. Getting errors when checking the desktop file with `desktop-file-validate`:

```
kevedit.desktop: warning: key "Encoding" in group "Desktop Entry" is deprecated
FATAL: Key Categories is not in .desktop file exactly once
```

* Please remove the `Encoding=` line
* Please add at least one of the main categories in the `Categories=` key.

Main Category | Description | Notes
-- | -- | --
AudioVideo | Application for presenting, creating, or processing multimedia (audio/video) |  
Audio | An audio application | Desktop entry must include AudioVideo as well
Video | A video application | Desktop entry must include AudioVideo as well
Development | An application for development |  
Education | Educational software |  
Game | A game |  
Graphics | Application for viewing, creating, or processing graphics |  
Network | Network application such as a web browser |  
Office | An office type application |  
Science | Scientific software |  
Settings | Settings applications | Entries may appear in a separate menu or as part of a 		"Control Center"
System | System application, "System Tools" such as say a log viewer or network monitor |  
Utility | Small utility application, "Accessories"

In addition, you could specify one or more from the longer list of [Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html).

Please test the result with `desktop-file-validate` and make sure it passes.

Reference:
https://travis-ci.org/AppImage/appimage.github.io/builds/288258109#L701-L702

**Comment by cknave** [comment]
Thanks! I'll reopen this to track this issue.

**Comment by cknave** [comment]
Fixes for the .desktop file have been released in 1.0.1.

**Comment by probonopd** [comment]
Thanks for adding a category; however it still doesn't seem to pass `desktop-file-validate`:

```
kevedit.desktop: error: value "Game" for string list key "Categories" in group "Desktop Entry" does not have a semicolon (';') as trailing character
```

The line should look like this:
```
Categories=Game;
```

Reference:
https://travis-ci.org/AppImage/appimage.github.io/builds/292688660#L701

**Comment by cknave** [comment]
Thanks, I'll update the file later today.

Is there some other check that's finding these problems? I'm using desktop-file-validate 0.23, and the only thing it's caught is the warning about Encoding being deprecated in the previous version.

```
$ equery b `which desktop-file-validate`
 * Searching for /usr/bin/desktop-file-validate ...
dev-util/desktop-file-utils-0.23 (/usr/bin/desktop-file-validate)
$ desktop-file-validate kevedit.desktop
$ echo $?
0
```

**Comment by probonopd** [comment]
I'm using the version of desktop-file-validate that comes with Ubuntu 14.04, and that version gives the error.

**Comment by cknave** [comment]
Looks like that's version 0.22. I guess they loosened the requirements in 0.23.

At any rate, updated the .desktop file and validated with 0.22, so the latest binaries should be good to go.

Thanks for your help!

**Comment by probonopd** [comment]
Thank you.
