### ISSUE TITLE
Support for both Font Mania COM and UPAL PLD files, as well as Plain CHR and PAL files

### ISSUE THREAD

**Issue by TheRealHamtaro126** [cknave/kevedit#21]
Support for these are needed for completeness with upcoming Zeta support, as well as backwards compatibiliry for FM and UPAL:
- Font Mania COM files, which are basically a CHR file wrapped in a TSR .COM file (Terminate and Stay Resident)
- CHR with size 8xNN (NN meaning size number Zeta can handle with Max being 16 and Min being 8)
- PAL with all 16 VGA colors
- UPAL PLD palettes are basically VGA palettes with 64 colors, and out of that, 16 are ever used**.
-(optional?) Possible Future Palette and Character Editor

And load/save to them as well,

**PLD is Formatted after the full EGA palette, where color indices 00h-06h is dark black thru purple, 14h is brown, 07h is dark white, and all the lighter colors from 0x38-0x3F

**Comment by asiekierka** [comment]
I was considering making a separate library to parse all these formats, as Zeta, libzoo and KevEdit could all benefit from it. ~~Perhaps even MegaZeux~~

**Comment by SaxxonPike** [comment]
Some code from Roton that handles loading different kinds of fonts: https://github.com/SaxxonPike/roton/blob/1140f1d3462e686682a2a7100522eab4c294b623/Source/Roton/Composers/Video/Glyphs/Impl/AutoDetectBinaryGlyphComposer.cs

**Comment by computirman** [comment]
.CHR and .PAL support has become the community standard since zedit2 supports it. Having to switch to DosBox in order to make these features available to Kevedit really reduces velocity when making modern games. Please consider revising.

**Comment by cknave** [comment]
In progress.

main branch now supports loading .chr and font mania .com character sets in SDL and DOS.
![Screenshot_20230308_224802](https://user-images.githubusercontent.com/4196901/223912850-76cc951a-1b87-4ecb-ac4c-0c3b3f1aa8e6.png)
![Screenshot_20230308_224819](https://user-images.githubusercontent.com/4196901/223912859-6d12a4d5-4c33-4c65-88f3-4bbfee61a56d.png)

**Comment by cknave** [comment]
And main now supports loading .pal files in SDL and DOS as well. I don't have any .pld files to try in my ZZT directory, so I'm leaning towards omitting that for now. It should be easy to add if it's needed.

![Screenshot_20230309_212100](https://user-images.githubusercontent.com/4196901/224209012-20353731-857b-4d0f-8ad9-0b4e89d84d00.png)

**Comment by TheRealHamtaro126** [comment]
Fonts are doing good, Now Palette files are in progress as of this time, Thanks Kev!!!

This is now closed, unless otherwise someone has any other questions, Go ahead and Reopen!

Thanks to everyone in the ZZT community for this gift, March 8th was my Birthday, I got giddy on the mailbox when I saw progress acutally being made, again, thanks!
