### ISSUE TITLE
Poppy audio in Windows when testing #play

### ISSUE THREAD

**Issue by ZZTGuy** [cknave/kevedit#31]
Whenever I try to test #play commands since the update, the audio pops at the start of the test before actually playing the notes. This makes short notes at the start inaudible. I've tried multiple audio output devices and the problem persists, so I'm not sure what to do.

**Comment by cknave** [comment]
I could reproduce this on my Windows machine which for some reason was set up to use floats as its default audio format. I updated the [audio code](https://github.com/cknave/kevedit/commit/0d65be27802316d98f47f0790e9ccdb602e26e31) in 1.1.2 to support more formats without using SDL's built in converter, and that seemed to work. Let me know if this is still an issue, @ZZTGuy, and I can reopen
