### ISSUE TITLE
Fill tool forces default color mode

### ISSUE THREAD

**Issue by DrDos0016** [cknave/kevedit#33]
When using the fill tool ("f" key) with something in the custom pattern buffer selected and default color mode disabled, the fill will use the color of the tile in the pattern buffer and not the currently selected color.

To reproduce: 
Put a blue gem in the pattern buffer.
Disable default color mode.
Change color to green.
Press "f" to fill a region.
The region will be filled with blue gems rather than green.

This also applies to the capital-F fill that uses the entire buffer as well.

**Comment by cknave** [comment]
Good find! This defect was introduced all the way back in 0.3.3 when flood fills were revamped

**Comment by cknave** [comment]
Fixed in 8380e5fe5a423e0066b0a41775a49411939ae3ff
