### ISSUE TITLE
Projectile Labels Are Backwards

### ISSUE THREAD

**Issue by DrDos0016** [cknave/kevedit#39]
When placing builtins with toggle-able projectile types, KevEdit's text is currently reporting the opposite. Tigers and Spinning Guns freshly placed without any adjustment will say they're using throwstars but will in fact shoot bullets. The actual integer value that stores this information is correct, it's just being reported incorrectly.

This can be quickly confirmed with DEMO.ZZT's tiger demonstration board which only has bullet shooting tigers, all of which are reported by KevEdit as having stars.

**Comment by cknave** [comment]
Doh! Fixed by @asiekierka in #37
