### ISSUE TITLE
Flood-filling objects without stats

### ISSUE THREAD

**Issue by kristomu** [cknave/kevedit#45]
Trying to flood-fill over a region of objects without stats causes a segmentation fault. The region has to have more than one object without stats, and manually overwriting them (with TAB, say) doesn't trigger it.

The problem seems to be in zztParamGetProperty: `return param->data[zztParamDatauseLocate(property)]` but `param` is a null pointer.

gdb gives this backtrace, whose line numbers may be suspect but otherwise might be of help!

```
#0  0x00005555555768f5 in zztParamGetProperty (param=0x0, 
    property=property@entry=7) at params.c:264
#1  0x000055555555bbf6 in floodselect (block=block@entry=0x555555ad1f50, 
    fillsel=..., x=11, y=<optimized out>) at misc.c:815
#2  0x000055555555bfee in dofloodfill (myeditor=0x555555b000c0, randomflag=0)
    at misc.c:894
#3  0x00005555555593be in keveditHandleKeypress (
    myeditor=myeditor@entry=0x555555b000c0) at kevedit.c:678
#4  0x0000555555559ba4 in kevedit (myeditor=myeditor@entry=0x555555b000c0)
    at kevedit.c:189
#5  0x0000555555558815 in main (argc=1, argv=0x7fffffffe128) at main.c:120
```

**Comment by cknave** [comment]
Fixed in version 1.1.3
