### ISSUE TITLE
Run length of 00 means 256 apparently

### ISSUE THREAD

**Issue by cknave** [cknave/kevedit#5]
See "RLE Lock" in https://museumofzzt.com/article/323/page/2/a-guide-to-zzt-lock-picking

**Comment by SaxxonPike** [comment]
ZZT's RLE loop decrements *before* checking to see if the counter is zero, which will cause a value of zero to wrap around to 255 as it's a byte internally. All other values in this case perform exactly as expected.

Implementation in Roton (UnpackTiles):
https://github.com/SaxxonPike/roton/blob/master/Source/Roton/Emulation/Core/Impl/GameSerializer.cs#L228

**Comment by cknave** [comment]
Thanks @SaxxonPike. A fix for this has been sitting in master for a while, I just need to release it: aeb76493ad93dd96147e63ef9c6a70b04b56c54d
