### ISSUE TITLE
SDL music testing is not working too well

### ISSUE THREAD

**Issue by cknave** [cknave/kevedit#9]
On linux, it clicks between each note. On mac and windows I don't hear anything.

**Comment by cknave** [comment]
I dumped the various frequency tables using dosbox debug, should be useful in rewriting the music testing code: https://gist.github.com/cknave/2409bb12207b9060eaf078394cc4ee88

**Comment by asiekierka** [comment]
[ZZT's own playback logic, now MIT-licensed](https://github.com/asiekierka/reconstruction-of-zzt/blob/master/SRC/SOUNDS.PAS)
